server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    # 拉取间隔时间(默认30)
    registry-fetch-interval-seconds: 5
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: api-passenger
logging:
  level:
    root: info